# Generated by Django 4.1.2 on 2022-11-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
