# Generated by Django 4.1.2 on 2022-11-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0004_alter_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
