# Generated by Django 4.1.2 on 2022-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=30)),
                ('name_of_the_food', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
