# Generated by Django 4.1.2 on 2022-11-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0007_specialmenu_alter_menu_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialmenu',
            old_name='sp_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='specialmenu',
            old_name='sp_name_of_the_food',
            new_name='name_of_the_food',
        ),
        migrations.RenameField(
            model_name='specialmenu',
            old_name='sp_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='specialmenu',
            old_name='sp_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='specialmenu',
            old_name='sp_type_of_meal',
            new_name='type_of_meal',
        ),
    ]
