# Generated by Django 4.1.2 on 2022-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0008_rename_sp_description_specialmenu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(),
        ),
    ]
