# Generated by Django 4.1.2 on 2022-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0009_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmenu',
            name='price',
            field=models.FloatField(),
        ),
    ]
