# Generated by Django 4.1.2 on 2022-12-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0015_alter_message_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='full_name',
            new_name='full_names',
        ),
    ]
