# Generated by Django 4.1.2 on 2022-12-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0016_rename_full_name_reservation_full_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='full_names',
            new_name='full_name',
        ),
    ]
