# Generated by Django 4.1.2 on 2022-12-11 15:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_kitchen', '0017_rename_full_names_reservation_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='specialmenu',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
