# Generated by Django 4.1.2 on 2022-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_of_publication', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='blog_images')),
                ('target_page', models.URLField()),
            ],
        ),
    ]
