# Generated by Django 4.1.2 on 2022-11-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_size',
            field=models.CharField(choices=[('big photo', 'big photo'), ('small photo', 'small photo')], default='small photo', max_length=15),
            preserve_default=False,
        ),
    ]
