# Generated by Django 4.1.2 on 2022-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_blog', '0002_post_photo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
