# Generated by Django 4.1.2 on 2022-11-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_blog', '0005_remove_post_target_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='you_tube_code',
            field=models.CharField(default='67ZO1VXZQ4o', max_length=20),
            preserve_default=False,
        ),
    ]
