# Generated by Django 4.1.2 on 2022-11-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_blog', '0007_foodlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodLike',
        ),
    ]
