# Generated by Django 4.1.2 on 2022-12-11 14:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='0', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
